SELECT * FROM OUR_FIRST_DB.PUBLIC.CUSTOMERS;

CREATE OR REPLACE TABLE OUR_FIRST_DB.PUBLIC.CUSTOMER_CLONE
CLONE  OUR_FIRST_DB.PUBLIC.CUSTOMERS;

// Validate the data

SELECT * FROM OUR_FIRST_DB.PUBLIC.CUSTOMER_CLONE;


//Update clone tabke 

UPDATE OUR_FIRST_DB.PUBLIC.CUSTOMER_CLONE
SET LAST_NAME = NULL;

SELECT * FROM OUR_FIRST_DB.PUBLIC.CUSTOMER_CLONE;

SELECT * FROM OUR_FIRST_DB.PUBLIC.CUSTOMERS;

// WE CAN clone table changes are not made to original table , even after clone table points to original table. 